### ISSUE TITLE
Push generic tweaks back to document-template

### ISSUE THREAD

**Issue by soxofaan** [EOEPCA/document-mlops#1]
I noticed this repo did some generic tweaks to the template repo https://github.com/EOEPCA/document-template, e.g.:
- 1dbe3741913ceaca05e2db6e8c01451f7bb2e343
- c95e568d52cf718baa54a2176f0a4c3404facfab
- 1d1f0a2fbb46dd9eaf55a27e1d36caf42e9579b8
- the WIP admonitions of 13beb75315f6c0607907578d7f0e39b3f855b1c3
- 7ab6893a9855788040eed1e56973582987e14c3f

I think it would be good for uniformity to push these upstream to the template repo

**Comment by CGuichard** [comment]
Merged in https://github.com/EOEPCA/document-template
